//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWithApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class info
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Appointment { get; set; }
        public string Technology { get; set; }
        public string Task { get; set; }
    }
}
