// <auto-generated />
namespace EFCodeFirstApproach.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add4));
        
        string IMigrationMetadata.Id
        {
            get { return "202205050640366_Add4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
